# Generated by Django 4.2.30 on 2026-06-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_leaverequest_dailyworklog_attendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="custom_permissions",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
