# Generated by Django 4.2.30 on 2026-06-29 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SOP", "SOP"),
                            ("Checklist", "Checklist"),
                            ("Template", "Template"),
                            ("Guide", "Guide"),
                            ("Policy", "Policy"),
                            ("Credential", "Credential"),
                            ("Other", "Other"),
                        ],
                        default="Guide",
                        max_length=50,
                    ),
                ),
                ("content", models.TextField()),
                ("is_confidential", models.BooleanField(default=False)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("All", "All"),
                            ("Admin Only", "Admin Only"),
                            ("Specific Roles", "Specific Roles"),
                        ],
                        default="All",
                        max_length=20,
                    ),
                ),
                ("allowed_roles", models.JSONField(blank=True, default=list)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("view_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authored_articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
