# Generated by Django 4.2.30 on 2026-06-29 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain_name", models.CharField(max_length=255, unique=True)),
                (
                    "registrar",
                    models.CharField(
                        choices=[
                            ("GoDaddy", "GoDaddy"),
                            ("Namecheap", "Namecheap"),
                            ("Google Domains", "Google Domains"),
                            ("Dynadot", "Dynadot"),
                            ("Other", "Other"),
                        ],
                        default="Namecheap",
                        max_length=50,
                    ),
                ),
                ("registered_date", models.DateField()),
                ("expiry_date", models.DateField()),
                ("auto_renew", models.BooleanField(default=False)),
                ("nameservers", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Expired", "Expired"),
                            ("Transferred", "Transferred"),
                        ],
                        default="Active",
                        max_length=20,
                    ),
                ),
                ("login_email", models.EmailField(blank=True, max_length=254)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="domains",
                        to="clients.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="domains",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SSLCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "issuer",
                    models.CharField(
                        choices=[
                            ("Let's Encrypt", "Let's Encrypt"),
                            ("Comodo", "Comodo"),
                            ("DigiCert", "DigiCert"),
                            ("Other", "Other"),
                        ],
                        default="Let's Encrypt",
                        max_length=50,
                    ),
                ),
                ("issued_date", models.DateField()),
                ("expiry_date", models.DateField()),
                ("auto_renew", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Valid", "Valid"),
                            ("Expired", "Expired"),
                            ("Expiring Soon", "Expiring Soon"),
                        ],
                        default="Valid",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ssl_certificates",
                        to="servers.domain",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Hosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("server_name", models.CharField(max_length=255)),
                (
                    "server_type",
                    models.CharField(
                        choices=[
                            ("VPS", "VPS"),
                            ("Shared", "Shared"),
                            ("Dedicated", "Dedicated"),
                            ("Cloud", "Cloud"),
                        ],
                        default="VPS",
                        max_length=20,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("DigitalOcean", "DigitalOcean"),
                            ("Vultr", "Vultr"),
                            ("AWS", "AWS"),
                            ("GCP", "GCP"),
                            ("Linode", "Linode"),
                            ("Hostinger", "Hostinger"),
                            ("Other", "Other"),
                        ],
                        default="DigitalOcean",
                        max_length=50,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("location", models.CharField(blank=True, max_length=100)),
                ("plan_name", models.CharField(blank=True, max_length=100)),
                (
                    "monthly_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("start_date", models.DateField()),
                ("renewal_date", models.DateField()),
                ("auto_renew", models.BooleanField(default=True)),
                ("username", models.CharField(blank=True, max_length=100)),
                ("root_access", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Suspended", "Suspended"),
                            ("Expired", "Expired"),
                        ],
                        default="Active",
                        max_length=20,
                    ),
                ),
                ("ram_gb", models.IntegerField(default=1)),
                ("storage_gb", models.IntegerField(default=20)),
                ("bandwidth_gb", models.IntegerField(default=1000)),
                ("cpu_cores", models.IntegerField(default=1)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hostings",
                        to="clients.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
