# Generated by Django 4.2.30 on 2026-06-29 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FollowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "follow_up_type",
                    models.CharField(
                        choices=[
                            ("Call", "Call"),
                            ("Email", "Email"),
                            ("Meeting", "Meeting"),
                            ("WhatsApp", "WhatsApp"),
                            ("Proposal", "Proposal"),
                            ("Demo", "Demo"),
                            ("Quotation", "Quotation"),
                            ("Check-in", "Check-in"),
                            ("Other", "Other"),
                        ],
                        default="Call",
                        max_length=50,
                    ),
                ),
                (
                    "related_to_type",
                    models.CharField(
                        choices=[
                            ("Lead", "Lead"),
                            ("Client", "Client"),
                            ("Project", "Project"),
                            ("General", "General"),
                        ],
                        default="General",
                        max_length=50,
                    ),
                ),
                ("related_to_id", models.IntegerField(blank=True, null=True)),
                ("scheduled_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Completed", "Completed"),
                            ("Missed", "Missed"),
                            ("Rescheduled", "Rescheduled"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Pending",
                        max_length=50,
                    ),
                ),
                ("reminder_sent", models.BooleanField(default=False)),
                ("reminder_at", models.DateTimeField(blank=True, null=True)),
                ("outcome", models.TextField(blank=True, null=True)),
                ("reschedule_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_followups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_followups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "next_follow_up",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="previous_followups",
                        to="followups.followup",
                    ),
                ),
            ],
        ),
    ]
