# Generated by Django 4.2.30 on 2026-06-29 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clients", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SEOKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=255)),
                ("target_url", models.URLField()),
                (
                    "search_engine",
                    models.CharField(
                        choices=[("Google", "Google"), ("Bing", "Bing")],
                        default="Google",
                        max_length=20,
                    ),
                ),
                ("country", models.CharField(default="US", max_length=10)),
                ("language", models.CharField(default="en", max_length=10)),
                ("current_position", models.IntegerField(default=0)),
                ("best_position", models.IntegerField(default=0)),
                ("monthly_search_volume", models.IntegerField(default=0)),
                ("difficulty", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Tracking", "Tracking"),
                            ("Not Tracking", "Not Tracking"),
                        ],
                        default="Tracking",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_keywords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="seo_keywords",
                        to="clients.client",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="seo_keywords",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SEOReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField()),
                ("organic_traffic", models.IntegerField(default=0)),
                ("organic_clicks", models.IntegerField(default=0)),
                ("impressions", models.IntegerField(default=0)),
                (
                    "avg_position",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("backlinks_total", models.IntegerField(default=0)),
                ("new_backlinks", models.IntegerField(default=0)),
                ("lost_backlinks", models.IntegerField(default=0)),
                ("top_pages", models.JSONField(blank=True, default=list)),
                ("issues_found", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True)),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="seo_reports/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seo_reports",
                        to="clients.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SEORankLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.IntegerField()),
                ("check_date", models.DateField(default=django.utils.timezone.now)),
                ("url_ranking", models.URLField(blank=True)),
                (
                    "keyword",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rank_logs",
                        to="seo.seokeyword",
                    ),
                ),
            ],
        ),
    ]
