# Generated by Django 4.2.30 on 2026-06-29 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentCalendarItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("Blog", "Blog"),
                            ("LinkedIn Post", "LinkedIn Post"),
                            ("Instagram", "Instagram"),
                            ("Twitter", "Twitter"),
                            ("Video", "Video"),
                            ("Email Newsletter", "Email Newsletter"),
                            ("Case Study", "Case Study"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("platform", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Idea", "Idea"),
                            ("Draft", "Draft"),
                            ("In Review", "In Review"),
                            ("Scheduled", "Scheduled"),
                            ("Published", "Published"),
                        ],
                        default="Idea",
                        max_length=20,
                    ),
                ),
                ("scheduled_date", models.DateTimeField(blank=True, null=True)),
                ("published_date", models.DateTimeField(blank=True, null=True)),
                ("content_url", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("engagement_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authored_content",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_content",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "campaign_type",
                    models.CharField(
                        choices=[
                            ("Email", "Email"),
                            ("Social Media", "Social Media"),
                            ("Google Ads", "Google Ads"),
                            ("WhatsApp", "WhatsApp"),
                            ("Content", "Content"),
                            ("SEO", "SEO"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Planning", "Planning"),
                            ("Active", "Active"),
                            ("Paused", "Paused"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Planning",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("budget", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="USD", max_length=10)),
                (
                    "actual_spent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("Facebook", "Facebook"),
                            ("Instagram", "Instagram"),
                            ("LinkedIn", "LinkedIn"),
                            ("Google", "Google"),
                            ("Twitter", "Twitter"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("target_audience", models.TextField(blank=True)),
                ("goal", models.TextField(blank=True)),
                ("expected_reach", models.IntegerField(default=0)),
                ("actual_reach", models.IntegerField(default=0)),
                ("clicks", models.IntegerField(default=0)),
                ("conversions", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
