# Generated by Django 4.2.30 on 2026-06-29 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("Lead", "Lead"),
                            ("Task", "Task"),
                            ("Follow-up", "Follow-up"),
                            ("Invoice", "Invoice"),
                            ("Project", "Project"),
                            ("System", "System"),
                        ],
                        default="System",
                        max_length=50,
                    ),
                ),
                (
                    "related_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("sent_via_email", models.BooleanField(default=False)),
                ("sent_via_whatsapp", models.BooleanField(default=False)),
                ("sent_via_push", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
